### PR TITLE
[PATCH]: Adding a new workflow to manage readme

### PR DESCRIPTION
**Pull request by ManavvGarg**
# New Pull Request

- **:pencil: What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added contributors addition automation to README with size being 50px x 50px overall

### CODE REVIEW

**Review by AbhijithGanesh — CHANGES_REQUESTED** [review]
Remove the changes done to Readme please

**Comment by cool-pants** [comment]
Have you tested this workflow on your fork? @ManavvGarg

**Review by AbhijithGanesh — APPROVED** [review]
LGTM

**Comment by ManavvGarg** [comment]
> I have! I am providing a screenshot for the same.

image

**Comment by AbhijithGanesh** [comment]
@cool-pants It works well!

**Comment by cool-pants** [comment]
Great, I am merging this then

**Pull request merged**
