### PR TITLE
Ic/issue templates

### PR DESCRIPTION
**Pull request by icebelly29**
## New Pull Request

- **:pencil: What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update (Issue template).

- **:pencil: What is the current behavior?** (You can also link to an open issue here)

- **:pencil: What is the new behavior (if this is a feature change)?**

- **:pencil: Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

### :white_check_mark: Check List (Check all the applicable boxes)

- [x] I have read [CONTRIBUTING.md](../CONTRIBUTING.md)
- [x] I have followed the [CODE OF CONDUCT](../CODE_OF_CONDUCT.md)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

### :scroll: Screenshots (If Applicable)

Original :
Updated :

### CODE REVIEW

**Review by AbhijithGanesh — APPROVED** [review]
LGTM!

**Review by AbhijithGanesh — CHANGES_REQUESTED** [review]
@icebelly29 The Bug reports have to be `.yaml` files to be enforced as templates! 

Sample bug and feature requests:

- [Data on Kubernetes's bug report](https://github.com/dokc/rap-god-api/blob/main/.github/ISSUE_TEMPLATE/bug.yaml)
- [GitHub relevant articles by GH](https://github.com/topics/form-template)

**Comment by icebelly29** [comment]
I just need to change the extensions right?

**Comment by AbhijithGanesh** [comment]
@icebelly29 No you need to reformat it to .yaml files! Can you please take a look at the sample I've attached ?

**Comment by icebelly29** [comment]
The changes have been made 👍

**Review by AbhijithGanesh — APPROVED** [review]
LGTM

**Pull request merged**
